// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDqpg9xgYKKny-Z48TSmlYZphcd0GGIAk',
    appId: '1:473106263594:android:7258fdc34e7472e8471d53',
    messagingSenderId: '473106263594',
    projectId: 'catapp-zero-dce',
    storageBucket: 'catapp-zero-dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJS6YzP0VlCvhn9F37s-Tk9wKN9QUPd0M',
    appId: '1:473106263594:ios:d4f70405a982ff40471d53',
    messagingSenderId: '473106263594',
    projectId: 'catapp-zero-dce',
    storageBucket: 'catapp-zero-dce.appspot.com',
    iosClientId:
        '473106263594-ifj13c3rlcamplqi50pl8vitfg02uefr.apps.googleusercontent.com',
    iosBundleId: 'com.magnificsoftware.cat',
  );
}
